# Generated by Django 3.2.25 on 2024-10-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_short', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldata',
            name='url',
            field=models.CharField(max_length=2048),
        ),
    ]
