# Generated by Django 3.2.25 on 2024-10-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_short', '0002_alter_urldata_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldata',
            name='url',
            field=models.TextField(),
        ),
    ]
